// Slide content for posts 1–3 (from posts.md), using real palettes from seasons.json.
export default (S) => {
  const hex = (id, name) => S[id].palette.find((c) => c.name.toLowerCase().includes(name))?.hex;
  const X = (id, name) => { const c = S[id].palette.find((c) => c.name.toLowerCase() === name.toLowerCase()); if (!c) throw new Error(`no ${name} in ${id}`); return c.hex; };
  const N = (id) => S[id].cardSwatches.map((c) => [c, S[id].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]);
  const R = "\n\nWant a personal colour review? Comment REVIEW 🎨\n\nFree scan at seasoncard.app (link in bio)\n\n";
  const cta = (title, hl) => ({ title, cta: true, v: { t: "mock", id: "soft-autumn", hl } });
  return [
    {
      n: 1,
      caption:
        "I'm a painter. When I mix a portrait, I don't think \"autumn\". I think temperature, value, contrast and saturation.\nSeasonal colour analysis is the same four questions. Season Card measures all four from a selfie, right in your browser. 🎨\nWhich one do you think is your strongest trait? 👇\n\nFree scan at seasoncard.app Save this to explain seasons to a friend.",
      tags: "#coloranalysis #colouranalysis #seasonalcoloranalysis #colortheory #colorseason",
      slides: [
        { hook: true, title: "Your colour season isn't a vibe. It's 4 measurements.", v: { t: "numbered" } },
        { kicker: "1 · Undertone", title: "Does your skin lean warm (golden) or cool (pink / blue)?", v: { t: "gradient", pos: 64 } },
        { kicker: "2 · Depth", title: "How light or deep are your skin, hair and eyes together?", v: { t: "value" } },
        { kicker: "3 · Contrast", title: "How different are they from each other?", v: { t: "heads" } },
        { kicker: "4 · Chroma", title: "Do clear, bright colours suit you, or soft, muted ones?", v: { t: "chroma" } },
        { kicker: "Mix all 4", title: "…and you land in 1 of 12 seasons.", body: "A painter calls it value, temperature and saturation.", v: { t: "grid12" } },
        cta("Get your 4 numbers free."),
      ],
    },
    {
      n: 2,
      caption:
        "\"Is this why I always look tired in black?\" Maybe, maybe not. Black is simply the deepest, highest-contrast neutral there is.\nIf your colouring is softer, a near-black often does the same job with less shadow. Which swap are you trying? 🖤\n\nFind out if black is your colour. Free scan at seasoncard.app",
      tags: "#coloranalysis #colorseason #wintercolors #softautumn #styletips",
      slides: [
        { hook: true, title: "Is black really “bad” on you?", v: { t: "black" } },
        { title: "Short answer: black isn't bad. It's **very deep + very high contrast.**", v: { t: "black", tags: ["Depth: max", "Contrast: max"] } },
        { title: "In seasonal theory, pure black lives mostly in the **Winter** palettes.", v: { t: "rows", ids: ["deep-winter", "true-winter", "bright-winter"] } },
        { title: "With **softer or lighter** colouring, black can cast shadows near the face.", v: { t: "shadow" } },
        { kicker: "Autumns, swap it for", title: "Espresso · dark chocolate · deep olive", v: { t: "swatches", list: [["#4B2E20", "Espresso"], ["#3B2A20", "Dark chocolate"], ["#4A4A2A", "Deep olive"]] } },
        { kicker: "Summers, swap it for", title: "Charcoal · deep navy · slate", v: { t: "swatches", list: [["#3A3D42", "Charcoal"], ["#1F2A44", "Deep navy"], ["#5A6573", "Slate"]] } },
        { kicker: "Springs, swap it for", title: "Warm navy · chocolate · dark teal", v: { t: "swatches", list: [["#26355E", "Warm navy"], ["#5A3A28", "Chocolate"], ["#1F5C5C", "Dark teal"]] } },
        cta("Still love black? Wear it away from your face. Find your “black” →"),
      ],
    },
    {
      n: 3,
      caption:
        "Soft and True Autumn wear the same family of colours: rust, olive, camel, teal. True Autumn wears them rich. Soft Autumn wears them as if a little grey was mixed in.\n(Painter tip: that \"grey mixed in\" is literally how I'd mix a Soft Autumn palette.) Save for shopping 🍂\n\nSave this. Free scan at seasoncard.app to see your chroma score.",
      tags: "#softautumn #trueautumn #coloranalysis #autumnpalette #colorseason",
      slides: [
        { hook: true, title: "Soft Autumn or True Autumn? The one difference.", v: { t: "fans", a: "soft-autumn", b: "true-autumn" } },
        { title: "Both are **warm.** The difference is **chroma**: how saturated the colour is.", v: { t: "chroma", a: "#C0632A", b: "#B08A70", la: "Rich", lb: "Muted" } },
        { kicker: "Soft Autumn", title: "Warm-neutral, medium, low contrast, **muted**", v: { t: "swatches", list: S["soft-autumn"].cardSwatches.map((c, i) => [c, ["Clay", "Honey", "Sage", "Soft teal"][i]]) } },
        { kicker: "True Autumn", title: "Warm, medium-deep, **rich and earthy**", v: { t: "swatches", list: S["true-autumn"].cardSwatches.map((c, i) => [c, ["Rust", "Mustard", "Olive", "Teal"][i]]) } },
        { kicker: "Same colour, two versions", title: "Orange", v: { t: "pair", a: ["#C98B6B", "Soft Autumn"], b: ["#D2691E", "True Autumn"] } },
        { kicker: "Same colour, two versions", title: "Green", v: { t: "pair", a: ["#9FA37E", "Soft Autumn"], b: ["#6D6A2F", "True Autumn"] } },
        cta("Not sure which you are? Your chroma score tells you.", "Chroma"),
      ],
    },
      {
      n: 5,
      caption: "The \"sage green everything\" trend isn't for everyone, and that's fine. Every season has *a* green. Which one have you been reaching for? 🌿\n\nFind your green. Free scan at seasoncard.app",
      tags: "#sagegreen #coloranalysis #softsummer #softautumn #colorseason",
      slides: [
        { hook: true, title: "Sage green looks grey on some people. Here's why.", v: { t: "single", c: "#9CAF88" } },
        { title: "Sage is **soft** (low chroma), **light-medium**, and slightly **warm-neutral.**", v: { t: "chroma", a: "#9CAF88", b: "#5FA36A", la: "Sage (soft)", lb: "Clear green" } },
        { kicker: "Best on", title: "Soft Autumn and Soft Summer", v: { t: "palettes", ids: ["soft-autumn", "soft-summer"] } },
        { kicker: "Good on", title: "Light Summer and Light Spring, in a lighter tint", v: { t: "pair", a: ["#9CAF88", "Sage"], b: ["#C5D1B8", "Light sage"] } },
        { kicker: "Tricky for", title: "Bright Winter and Bright Spring. It can look dusty next to clear colouring.", v: { t: "palettes", ids: ["bright-winter", "bright-spring"] } },
        { kicker: "Their green instead", title: "Bright seasons → mint or jade. Deep seasons → deep olive or forest.", v: { t: "swatches", list: [["#98E0C2", "Mint"], ["#00A36C", "Jade"], ["#4A5D23", "Deep olive"], ["#2F4F2F", "Forest"]] } },
        cta("Which green is yours? Your 36-colour palette is in the full report."),
      ],
    },
    {
      n: 6,
      caption: "This is a big reason people get different seasons from different quizzes, apps, even analysts working from photos. Light changes everything. Get the light right and the result gets more consistent. 💡\n\nSave the checklist. Try the free scan by a window at seasoncard.app",
      tags: "#undertone #coloranalysis #skinundertone #colorseason #lighting",
      slides: [
        { hook: true, title: "Warm in one photo, cool in the next? Your skin didn't change.", v: { t: "faces", tints: [["rgba(255,170,90,.35)", "Warm bulb"], ["rgba(110,150,210,.35)", "Shade"]] } },
        { title: "**Warm bulbs** push skin yellow-orange, so everyone looks warm.", v: { t: "faces", tints: [["rgba(255,160,70,.45)", "illustration"]] } },
        { title: "**Shade and overcast** push skin blue, so everyone looks cool.", v: { t: "faces", tints: [["rgba(100,140,210,.45)", "illustration"]] } },
        { title: "**Phone cameras auto-correct** white balance, and beauty filters change skin.", v: { t: "bigtext", text: "WB · AUTO", sub: "Your camera guesses the light, and often guesses wrong." } },
        { title: "Screens differ too. The same photo looks different on two phones.", v: { t: "pair", a: ["#C98B6B", "Phone A"], b: ["#C6977F", "Phone B"] } },
        { kicker: "Best light", title: "Indirect daylight, facing a window, no direct sun.", v: { t: "bigtext", text: "☀︎ → 🪟 → you", sub: "Window in front of you, not behind." } },
        { kicker: "Checklist", title: "Before any colour analysis:", v: { t: "checklist", items: ["No filter", "No (or light) makeup", "Hair visible", "Facing a window"] } },
        cta("Season Card checks your light first, then it measures."),
      ],
    },
    {
      n: 7,
      caption: "\"Find her best pink\" videos keep going viral because the right pink changes everything. No faces needed: just figure out which family you're in. A, B, C or D? 👇\n\nComment your letter. Free scan at seasoncard.app to check.",
      tags: "#pink #coloranalysis #colorseason #springcolors #summercolors",
      slides: [
        { hook: true, title: "One of these pinks is yours. 🌸", v: { t: "letters", list: [["#FF8C7A", "A"], ["#C4A0A0", "B"], ["#C08081", "C"], ["#E0218A", "D"]] } },
        { title: "Myth: \"warm undertones can't wear pink.\" Truth: **every season has a pink.**", v: { t: "bigtext", text: "✕", sub: "\"Warm skin can't wear pink\"" } },
        { kicker: "A · Springs", title: "Warm coral-pink, peach-pink", v: { t: "swatches", list: [["#F4A2A0", "Peach-pink"], ["#FF8C7A", "Coral-pink"]] } },
        { kicker: "B · Summers", title: "Cool rose, soft raspberry, powder pink", v: { t: "swatches", list: [["#EBC3CC", "Powder"], ["#C4A0A0", "Cool rose"], ["#B03A5B", "Raspberry"]] } },
        { kicker: "C · Autumns", title: "Dusty rose-brown, terracotta pink", v: { t: "swatches", list: [["#C08081", "Dusty rose"], ["#B5705A", "Terracotta pink"]] } },
        { kicker: "D · Winters", title: "Icy pink or vivid fuchsia", v: { t: "swatches", list: [["#F4D7E3", "Icy pink"], ["#E0218A", "Fuchsia"]] } },
        cta("Guess your letter in the comments 👇 then check it free."),
      ],
    },
    {
      n: 8,
      caption: "Palette-only edition of \"guess her season\". How many did you get? Drop your score /4 👇 (No peeking at slide 6.)\n\nComment your score. Free Season Card at seasoncard.app",
      tags: "#guesstheseason #coloranalysis #colorseason #colorpalette #colouranalysis",
      slides: [
        { hook: true, title: "Guess the season from the palette alone. 🤔", v: { t: "bigtext", text: "?", sub: "4 palettes · answers on slide 6" } },
        { kicker: "Palette 1", title: "Guess!", v: { t: "letters", list: [["#F7C59F", ""], ["#9ED9CC", ""], ["#F5E1A4", ""], ["#F4A2A0", ""]] } },
        { kicker: "Palette 2", title: "Guess!", v: { t: "letters", list: [["#6D0F2B", ""], ["#000000", ""], ["#009B77", ""], ["#1B2A4A", ""]] } },
        { kicker: "Palette 3", title: "Guess!", v: { t: "letters", list: [["#7D8FA3", ""], ["#A28CA0", ""], ["#C4A0A0", ""], ["#9C8F87", ""]] } },
        { kicker: "Palette 4", title: "Guess!", v: { t: "letters", list: [["#B7410E", ""], ["#D4A017", ""], ["#708238", ""], ["#1F6F6B", ""]] } },
        { kicker: "Answers", title: "How many did you get?", v: { t: "answers", list: [[["#F7C59F", "#9ED9CC", "#F5E1A4", "#F4A2A0"], "Light Spring"], [["#6D0F2B", "#000000", "#009B77", "#1B2A4A"], "Deep Winter"], [["#7D8FA3", "#A28CA0", "#C4A0A0", "#9C8F87"], "Soft Summer"], [["#B7410E", "#D4A017", "#708238", "#1F6F6B"], "True Autumn"]] } },
        cta("Now get your own 4-colour card."),
      ],
    },
    {
      n: 9,
      caption: "If one quiz said Soft Summer and another said Soft Autumn, you may be right on the border. They're neighbours: same softness, same depth, same low contrast. The only real split is cool-neutral vs warm-neutral. That's why Season Card always shows a runner-up. Which side are you on? 🌫️🍂\n\nSee your runner-up season. Free scan at seasoncard.app",
      tags: "#softsummer #softautumn #coloranalysis #colorseason #undertone",
      slides: [
        { hook: true, title: "Soft Summer or Soft Autumn? It's one question.", v: { t: "fans", a: "soft-summer", b: "soft-autumn" } },
        { title: "Both are **soft, medium, low-contrast.** They're next-door neighbours.", v: { t: "palettes", ids: ["soft-summer", "soft-autumn"] } },
        { title: "The one question: **cool-neutral or warm-neutral?**", v: { t: "gradient", pos: 50, lo: "Cool-neutral", hi: "Warm-neutral" } },
        { kicker: "Soft Summer", title: "Cool-neutral, dusty, **grey-blue based**", v: { t: "swatches", list: S["soft-summer"].cardSwatches.map((c) => [c, S["soft-summer"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Soft Autumn", title: "Warm-neutral, earthy, **golden-grey based**", v: { t: "swatches", list: S["soft-autumn"].cardSwatches.map((c) => [c, S["soft-autumn"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Window test", title: "Camel vs dusty rose under your chin. Which one makes your skin look **more even?**", v: { t: "pair", a: [hex("soft-autumn", "camel") ?? "#B8946A", "Camel → Soft Autumn"], b: [hex("soft-summer", "dusty rose") ?? "#C49A9C", "Dusty rose → Soft Summer"] } },
        cta("Your result shows your season **and your runner-up**, because neighbours are close.", undefined),
      ],
    },
    {
      n: 11,
      caption: "Gold vs silver is the easiest undertone test you can do at home, and it beats staring at your veins. Daylight, no filter, foil under your chin. Which one won for you? 🥇🥈\n\nComment gold, silver or both. Free scan at seasoncard.app",
      tags: "#goldvssilver #undertone #coloranalysis #jewelry #colorseason",
      slides: [
        { hook: true, title: "Gold or silver? Try this, not the vein test.", v: { t: "swatches", list: [["linear-gradient(135deg,#8C6A1E,#E9C766 45%,#B8902C 60%,#F3DC8A)", "Gold"], ["linear-gradient(135deg,#7D8086,#E6E8EB 45%,#A3A7AD 60%,#F2F3F5)", "Silver"]] } },
        { title: "The vein test is unreliable. **Light, skin thickness and the room** all change what you see.", v: { t: "bigtext", text: "✕", sub: "\"Blue veins = cool, green veins = warm\"" } },
        { kicker: "Better test", title: "Hold **real gold and silver** (or foil) under your chin, facing a window.", v: { t: "checklist", items: ["Daylight, no direct sun", "No filter, bare skin", "One metal at a time", "Look at your skin, not the metal"] } },
        { title: "Gold makes your skin look **even and glowy?** Likely warm. Silver does it? Likely cool.", v: { t: "pair", a: ["linear-gradient(135deg,#8C6A1E,#E9C766 45%,#B8902C 60%,#F3DC8A)", "Even with gold → warm"], b: ["linear-gradient(135deg,#7D8086,#E6E8EB 45%,#A3A7AD 60%,#F2F3F5)", "Even with silver → cool"] } },
        { title: "**Both look fine?** You may be neutral. Rose gold and brushed metals are your friends.", v: { t: "single", c: "linear-gradient(135deg,#9A5A5E,#E6B2A6 45%,#B76E79 60%,#F1CFC6)", label: "Rose gold" } },
        { kicker: "Best metal, by season", title: "A few examples:", v: { t: "table", rows: [["#E9C766", "Soft Autumn", S["soft-autumn"].metals.best], ["#C9A24A", "Deep Autumn", S["deep-autumn"].metals.best], ["#C9CCD1", "Soft Summer", S["soft-summer"].metals.best], ["#E6E8EB", "Deep Winter", S["deep-winter"].metals.best]] } },
        { title: "Your full report lists your **best, good and skip** metals.", cta: true, v: { t: "mock", id: "soft-autumn", note: `Metals: ${S["soft-autumn"].metals.best} · skip ${S["soft-autumn"].metals.skip.toLowerCase()}` } },
      ],
    },
    {
      n: 12,
      caption: "Celebrity season debates are fun, but they show why photo-based typing is hard: stage lighting, dyed hair, makeup and editing all move the needle. Want a fairer read on yourself? Daylight, no filter. 💡\n\nFree scan at seasoncard.app. Use daylight!",
      tags: "#celebritycoloranalysis #coloranalysis #colorseason #undertone #beautytok",
      slides: [
        { hook: true, title: "Why can't the internet agree on celebrity colour seasons?", v: { t: "grid12" } },
        { title: "Same person, five comment sections, five different seasons. **Here's why.**", v: { t: "bigtext", text: "?", sub: "No photo can settle it." } },
        { kicker: "Reason 1", title: "**Stage and studio lighting** push skin warm or cool, photo to photo.", v: { t: "faces", tints: [["rgba(255,160,70,.45)", "Warm gel · illustration"], ["rgba(100,140,210,.45)", "Cool gel · illustration"]] } },
        { kicker: "Reason 2", title: "**Hair colour changes.** Dyed hair shifts contrast and warmth.", v: { t: "swatches", list: [["#E8DCC4", "Platinum"], ["#A63A1F", "Copper red"], ["#1E1612", "Jet black"]] } },
        { kicker: "Reason 3", title: "**Makeup and photo editing** change undertone and contrast.", v: { t: "bigtext", text: "EDITED", sub: "Retouching, filters, colour grading" } },
        { title: "So typing anyone from red-carpet photos is a guess. **That includes you from a filtered selfie.**", v: { t: "checklist", items: ["No filter", "No (or light) makeup", "Hair visible", "Facing a window"] } },
        cta("Unfiltered + daylight = your most consistent result. Try yours free."),
      ],
    },
    {
      n: 13,
      caption: "Burgundy season is here 🍷 but \"burgundy\" is really a range, from cool wine to warm oxblood. Both deep seasons can wear it; the temperature decides which one. Which side are you? Wine or brick?\n\nComment wine or brick. Free scan at seasoncard.app",
      tags: "#burgundy #deepautumn #deepwinter #coloranalysis #fallfashion",
      slides: [
        { hook: true, title: "Burgundy looks expensive on some people. On others: tired.", v: { t: "single", c: "#6D0F2B" } },
        { title: "Burgundy is **deep**, so both deep seasons can wear it. **Temperature** decides the version.", v: { t: "pair", a: [hex("deep-winter", "merlot"), "Cool wine"], b: [hex("deep-autumn", "oxblood"), "Warm oxblood"] } },
        { kicker: "Deep Winter burgundy", title: "Cool, berry, **wine**", v: { t: "swatches", list: [[hex("deep-winter", "merlot"), "Merlot"], [hex("deep-winter", "garnet"), "Garnet"], [hex("deep-winter", "cranberry"), "Cranberry"]] } },
        { kicker: "Deep Autumn burgundy", title: "Warm, brick, **oxblood-brown**", v: { t: "swatches", list: [[hex("deep-autumn", "oxblood"), "Oxblood"], [hex("deep-autumn", "mahogany"), "Mahogany"], [hex("deep-autumn", "brick"), "Brick"]] } },
        { kicker: "Lighter or softer colouring?", title: "Try a softened version: **raspberry** (Summer) or **rosewood** (Soft Autumn).", v: { t: "pair", a: ["#B03A5B", "Raspberry"], b: ["#9E5B5B", "Rosewood"] } },
        { kicker: "Quick check", title: "If burgundy makes your lips look pale, it's too deep. **Go one step lighter.**", v: { t: "pair", a: ["#6D0F2B", "Too deep?"], b: ["#9E3A4F", "One step lighter"] } },
        cta("Get your season's exact burgundy in your 36-colour palette."),
      ],
    },
    {
      n: 14,
      caption: "Brown is the new black this autumn 🍫 but there are many browns. A warm golden chocolate and a cool rosy cocoa do completely different things next to your face. Which one is yours? A, B, C or D? 👇\n\nComment your letter. Free scan at seasoncard.app to check.",
      tags: "#chocolatebrown #coloranalysis #colorseason #fallfashion #autumnpalette",
      slides: [
        { hook: true, title: "Swapping black for brown? Pick the right brown. 🍫", v: { t: "letters", list: [[hex("true-spring", "golden brown"), "A"], [hex("true-summer", "rose brown"), "B"], [hex("true-autumn", "chocolate"), "C"], [hex("deep-winter", "cool espresso"), "D"]] } },
        { title: "Brown isn't one colour. It changes in **temperature** (golden vs rosy) and **depth** (milky vs espresso).", v: { t: "gradient", pos: 50, lo: "Rosy cocoa", hi: "Golden chocolate" } },
        { kicker: "A · Springs", title: "Light, **golden** browns: caramel, golden brown", v: { t: "swatches", list: [[hex("true-spring", "golden brown"), "Golden brown"], ["#C68E5A", "Caramel"]] } },
        { kicker: "B · Summers", title: "Soft, **rosy** browns: cocoa, rose brown", v: { t: "swatches", list: [[hex("soft-summer", "cocoa"), "Cocoa"], [hex("true-summer", "rose brown"), "Rose brown"]] } },
        { kicker: "C · Autumns", title: "Rich, **warm** browns: chocolate, coffee, espresso", v: { t: "swatches", list: [[hex("true-autumn", "chocolate"), "Chocolate"], [hex("soft-autumn", "coffee"), "Coffee"], [hex("deep-autumn", "espresso"), "Espresso"]] } },
        { kicker: "D · Winters", title: "Deep, **cool** browns, almost black: cool espresso", v: { t: "swatches", list: [[hex("deep-winter", "cool espresso"), "Cool espresso"], ["#2B2220", "Black-brown"]] } },
        cta("Comment your letter 👇 then see your exact browns free."),
      ],
    },
    {
      n: 15,
      caption: "True Winter and Deep Winter both look amazing in black and white, so how do you tell them apart? It's depth. True Winter is pure cool. Deep Winter is deep first, cool second. Which one are you? ❄️🖤\n\nSee your season and runner-up. Free scan at seasoncard.app",
      tags: "#truewinter #deepwinter #coloranalysis #wintercolors #colorseason",
      slides: [
        { hook: true, title: "True Winter or Deep Winter? Here's the one difference.", v: { t: "fans", a: "true-winter", b: "deep-winter" } },
        { title: "Both are **high contrast** and **clear.** Both can wear black. The split is **depth vs coolness.**", v: { t: "palettes", ids: ["true-winter", "deep-winter"] } },
        { kicker: "True Winter", title: "**Cool first.** Icy, blue-based, crisp", v: { t: "swatches", list: S["true-winter"].cardSwatches.map((c) => [c, S["true-winter"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Deep Winter", title: "**Deep first.** Dark, rich, cool-neutral", v: { t: "swatches", list: S["deep-winter"].cardSwatches.map((c) => [c, S["deep-winter"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Signature colours", title: "True Winter goes **vivid.** Deep Winter goes **dark and rich.**", v: { t: "pair", a: [hex("true-winter", "fuchsia"), "True Winter fuchsia"], b: [hex("deep-winter", "plum"), "Deep Winter plum"] } },
        { kicker: "Quick check", title: "Do **icy pastels** light you up, or wash you out? Light up → True Winter. Wash out → Deep Winter.", v: { t: "pair", a: [hex("true-winter", "icy lemon"), "Icy lemon"], b: [hex("deep-winter", "cool espresso"), "Cool espresso"] } },
        cta("Your result shows your season **and your runner-up.**", "Depth"),
      ],
    },
    {
      n: 16,
      caption: "Butter yellow is having a moment, and it's one of the hardest colours to wear well. Next to the wrong face it reads as sallow. Here's who it's made for, and what to wear if it's not you 🧈\n\nFind your yellow. Free scan at seasoncard.app",
      tags: "#butteryellow #coloranalysis #lightspring #colorseason #springcolors",
      slides: [
        { hook: true, title: "Butter yellow makes some people glow and others look sick. Here's why.", v: { t: "single", c: hex("light-spring", "butter yellow") } },
        { title: "Butter yellow is **light, warm and fairly clear.** It wants colouring that is too.", v: { t: "chroma", a: hex("light-spring", "butter yellow"), b: hex("soft-autumn", "buttermilk"), la: "Butter (clear)", lb: "Buttermilk (muted)" } },
        { kicker: "Made for", title: "Light Spring", v: { t: "palettes", ids: ["light-spring"] } },
        { kicker: "Cool and light?", title: "Summers: try a **pale, cool lemon** instead.", v: { t: "pair", a: [hex("light-summer", "pale lemon"), "Pale lemon"], b: [hex("true-summer", "light lemon"), "Light lemon"] } },
        { kicker: "Warm but muted?", title: "Soft and True Autumn: go **buttermilk or butterscotch.**", v: { t: "pair", a: [hex("soft-autumn", "buttermilk"), "Buttermilk"], b: [hex("true-autumn", "butterscotch"), "Butterscotch"] } },
        { kicker: "Winters", title: "Skip butter. **Icy lemon** or a sharp **lemon** works better.", v: { t: "pair", a: [hex("true-winter", "icy lemon"), "Icy lemon"], b: ["#FFEA2E", "Lemon"] } },
        cta("Your 36-colour palette shows your exact yellow."),
      ],
    },
    {
      n: 17,
      caption: "Red lipstick, red dress, red nails: there's a red for every season, but it's rarely the same red. Orange-red, blue-red, brick or rose? Which one has always worked for you? 💄\n\nComment your red. Free scan at seasoncard.app",
      tags: "#redlipstick #coloranalysis #colorseason #makeuptips #beautytok",
      slides: [
        { hook: true, title: "Everyone can wear red. Just not the same red. 💋", v: { t: "letters", list: [[hex("true-spring", "tomato"), "A"], [hex("light-summer", "soft red"), "B"], [hex("deep-autumn", "rich tomato"), "C"], [hex("true-winter", "cherry red"), "D"]] } },
        { title: "Red shifts in **temperature** (orange vs blue) and **chroma** (clear vs soft).", v: { t: "gradient", pos: 50, lo: "Blue-red", hi: "Orange-red" } },
        { kicker: "A · Springs", title: "Clear, warm **orange-reds and tomato**", v: { t: "swatches", list: [[hex("true-spring", "tomato"), "Tomato"], [hex("bright-spring", "true red"), "True red"]] } },
        { kicker: "B · Summers", title: "Soft, cool **rose-reds and raspberry**", v: { t: "swatches", list: [[hex("light-summer", "soft red"), "Soft red"], ["#B03A5B", "Raspberry"]] } },
        { kicker: "C · Autumns", title: "Warm, earthy **brick and rich tomato**", v: { t: "swatches", list: [[hex("soft-autumn", "soft tomato"), "Soft tomato"], [hex("deep-autumn", "rich tomato"), "Rich tomato"]] } },
        { kicker: "D · Winters", title: "Clear, cool **cherry and scarlet**", v: { t: "swatches", list: [[hex("true-winter", "cherry red"), "Cherry red"], [hex("bright-winter", "scarlet"), "Scarlet"]] } },
        cta("Your full report includes your exact lip shades."),
      ],
    },
    {
      n: 18,
      caption: "Light Spring and Light Summer are the two seasons people mix up most. Both are light and delicate. One is peachy and warm, the other is rosy and cool. Peach or powder pink: which looks better on you? 🍑🩷\n\nComment peach or pink. Free scan at seasoncard.app",
      tags: "#lightspring #lightsummer #coloranalysis #colorseason #pastels",
      slides: [
        { hook: true, title: "Light Spring or Light Summer? Do the peach test.", v: { t: "fans", a: "light-spring", b: "light-summer" } },
        { title: "Both are **light** with **low-to-medium contrast.** The split is **warm vs cool.**", v: { t: "palettes", ids: ["light-spring", "light-summer"] } },
        { kicker: "Light Spring", title: "**Warm and clear.** Coral, apricot, seafoam", v: { t: "swatches", list: S["light-spring"].cardSwatches.map((c) => [c, S["light-spring"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Light Summer", title: "**Cool and soft.** Rose pink, powder blue, lavender", v: { t: "swatches", list: S["light-summer"].cardSwatches.map((c) => [c, S["light-summer"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Peach test", title: "Hold peach and powder pink under your chin, facing a window. Which makes your skin look **more even?**", v: { t: "pair", a: ["#FFC7AE", "Peach → Light Spring"], b: ["#EBC3CC", "Powder pink → Light Summer"] } },
        { kicker: "Both look fine?", title: "You might sit right on the border. That's what a **runner-up season** is for.", v: { t: "bigtext", text: "🍑 ↔ 🩷", sub: "Neighbours share a lot of colours" } },
        cta("See your season **and your runner-up**, free."),
      ],
    },
    {
      n: 19,
      caption: 'Soft Autumn is one of the most common results and one of the most confused. If 4 of these 5 are you, you might be one. How many did you tick? 🍂👇\n\nComment your number. Check your season free at seasoncard.app',
      tags: '#softautumn #coloranalysis #colorseason #autumnpalette #seasonalcoloranalysis',
      slides: [
        { hook: true, title: "5 signs you're a Soft Autumn 🍂", v: { t: "swatches", list: S["soft-autumn"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Sign 1 · Skin", title: 'Warm-neutral. Your skin tans **golden-beige**, never pink.', v: { t: "gradient", pos: 64, lo: "Cool", hi: "Warm" } },
        { kicker: "Sign 2 · Hair", title: 'Hair is **golden or mousy** light-to-medium brown, often with no strong contrast.', v: { t: "swatches", list: S["soft-autumn"].hair.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 3 · Eyes", title: 'Eyes are **soft**: hazel, green or grey-brown, never icy.', v: { t: "swatches", list: S["soft-autumn"].eyes.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 4 · What looks wrong", title: '**Black, pure white and neon brights** look harsh or pasted on.', v: { t: "swatches", list: S["soft-autumn"].avoid.slice(0, 3).map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 5 · What looks right", title: 'Muted warm colours like **clay, honey, sage and soft teal** make you look rich.', v: { t: "palettes", ids: ["soft-autumn"] } },
        cta("Ticked 4 or 5? Check it free. Your result shows a runner-up too."),
      ],
    },
    {
      n: 20,
      caption: 'Deep Winter: the season that actually wears black well. If 4 of these 5 are you, you might be one. How many did you tick? 🖤👇\n\nComment your number. Check your season free at seasoncard.app',
      tags: '#deepwinter #coloranalysis #colorseason #wintercolors #seasonalcoloranalysis',
      slides: [
        { hook: true, title: "5 signs you're a Deep Winter 🖤", v: { t: "swatches", list: S["deep-winter"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Sign 1 · Skin", title: 'Cool-neutral skin, anywhere from **porcelain to deep**, that looks best in strong contrast.', v: { t: "gradient", pos: 35, lo: "Cool", hi: "Warm" } },
        { kicker: "Sign 2 · Hair", title: 'Hair is **very dark brown to black**.', v: { t: "swatches", list: S["deep-winter"].hair.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 3 · Eyes", title: 'Eyes are **dark and intense**.', v: { t: "swatches", list: S["deep-winter"].eyes.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 4 · What looks wrong", title: '**Pastels and muted earth tones** wash you out.', v: { t: "swatches", list: S["deep-winter"].avoid.slice(0, 3).map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 5 · What looks right", title: '**Black, pure white and jewel tones** (true red, emerald, sapphire, plum) look powerful.', v: { t: "palettes", ids: ["deep-winter"] } },
        cta("Ticked 4 or 5? Check it free. Your result shows a runner-up too."),
      ],
    },
    {
      n: 21,
      caption: "Light Summer looks best in colours most people call 'too soft'. If 4 of these 5 are you, you might be one. How many did you tick? 🩵👇\n\nComment your number. Check your season free at seasoncard.app",
      tags: '#lightsummer #coloranalysis #colorseason #summercolors #seasonalcoloranalysis',
      slides: [
        { hook: true, title: "5 signs you're a Light Summer 🩵", v: { t: "swatches", list: S["light-summer"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Sign 1 · Skin", title: 'Fair to light skin with a **cool, rosy** cast.', v: { t: "gradient", pos: 25, lo: "Cool", hi: "Warm" } },
        { kicker: "Sign 2 · Hair", title: 'Hair is **ash or pale golden-ash**.', v: { t: "swatches", list: S["light-summer"].hair.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 3 · Eyes", title: 'Eyes are **soft blue, grey or green**.', v: { t: "swatches", list: S["light-summer"].eyes.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 4 · What looks wrong", title: '**Black, orange and heavy earth tones** overpower you.', v: { t: "swatches", list: S["light-summer"].avoid.slice(0, 3).map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 5 · What looks right", title: 'Watercolour shades like **powder blue, rose pink and lavender** make you look fresh.', v: { t: "palettes", ids: ["light-summer"] } },
        cta("Ticked 4 or 5? Check it free. Your result shows a runner-up too."),
      ],
    },
    {
      n: 22,
      caption: 'True Spring is the warmest, sunniest season. If 4 of these 5 are you, you might be one. How many did you tick? 🌼👇\n\nComment your number. Check your season free at seasoncard.app',
      tags: '#truespring #coloranalysis #colorseason #springcolors #seasonalcoloranalysis',
      slides: [
        { hook: true, title: "5 signs you're a True Spring 🌼", v: { t: "swatches", list: S["true-spring"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Sign 1 · Skin", title: 'The warmest Spring: **golden or peachy** skin.', v: { t: "gradient", pos: 85, lo: "Cool", hi: "Warm" } },
        { kicker: "Sign 2 · Hair", title: 'Hair has **honey, strawberry or copper** in it.', v: { t: "swatches", list: S["true-spring"].hair.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 3 · Eyes", title: 'Eyes are **bright**: green, aqua or warm hazel.', v: { t: "swatches", list: S["true-spring"].eyes.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 4 · What looks wrong", title: '**Cool greys and icy pastels** leave you looking flat.', v: { t: "swatches", list: S["true-spring"].avoid.slice(0, 3).map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 5 · What looks right", title: 'Clear, sunny colours like **coral, marigold and turquoise** make you glow.', v: { t: "palettes", ids: ["true-spring"] } },
        cta("Ticked 4 or 5? Check it free. Your result shows a runner-up too."),
      ],
    },
    {
      n: 23,
      caption: "Unpopular opinion: pure white isn't the 'safe' choice. On most people a softer white looks fresher. Which white is yours? A, B, C or D? 🤍👇\n\nComment your letter. Free scan at seasoncard.app",
      tags: "#whiteoutfit #coloranalysis #colorseason #styletips #capsulewardrobe",
      slides: [
        { hook: true, title: "Stop wearing pure white. Unless you're a Winter. 🤍", v: { t: "letters", list: [["#FFFFFF", "A"], ["#F6F4EF", "B"], ["#FFF6E5", "C"], ["#F0E1C3", "D"]] } },
        { title: "Whites aren't all the same. They differ in **temperature** and **brightness.**", v: { t: "gradient", pos: 50, lo: "Cool, bright white", hi: "Warm, soft cream" } },
        { kicker: "A · Winters", title: "**Optic or pure white.** Your contrast can take it.", v: { t: "swatches", list: [["#FFFFFF", "Optic White"], ["#FAFAFA", "Pure White"]] } },
        { kicker: "B · Summers", title: "**Soft white.** A little grey, a little cool.", v: { t: "swatches", list: [["#F6F4EF", "Soft White"], [S["light-summer"].neutrals[1].hex, S["light-summer"].neutrals[1].name]] } },
        { kicker: "C · Springs", title: "**Ivory.** Warm and clear.", v: { t: "swatches", list: [["#FFF6E5", "Ivory"], ["#FBF0D9", "Warm Ivory"]] } },
        { kicker: "D · Autumns", title: "**Cream and oatmeal.** Warm and soft.", v: { t: "swatches", list: [["#F0E1C3", "Cream"], ["#E3D4BC", "Oatmeal"]] } },
        cta("Comment your letter 👇 then find your exact white free."),
      ],
    },
    {
      n: 24,
      caption: "Navy is the easiest swap for black, but there's a navy for every season: soft, grey, warm or ink. Which one is yours? A, B, C or D? 💙👇\n\nComment your letter. Free scan at seasoncard.app",
      tags: "#navy #coloranalysis #colorseason #capsulewardrobe #styletips",
      slides: [
        { hook: true, title: "Navy is the new black. But which navy? 💙", v: { t: "letters", list: [["#2F4F86", "A"], ["#5A6A8A", "B"], ["#1D3847", "C"], ["#1A2A5A", "D"]] } },
        { title: "Navy works for almost everyone because it's **dark without being harsh.** The trick is the **undertone.**", v: { t: "gradient", pos: 50, lo: "Grey-blue navy", hi: "Warm teal navy" } },
        { kicker: "A · Springs", title: "**Bright, warm navy**", v: { t: "swatches", list: [["#2F4F86", "Bright Navy"], ["#4C6390", "Soft Navy"]] } },
        { kicker: "B · Summers", title: "**Soft, greyed navy**", v: { t: "swatches", list: [["#5A6A8A", "Grey Navy"], ["#45506A", "Slate Navy"]] } },
        { kicker: "C · Autumns", title: "**Teal-leaning navy**", v: { t: "swatches", list: [["#1D3847", "Teal Navy"], ["#647A89", "Dusty Denim"]] } },
        { kicker: "D · Winters", title: "**Deep, ink navy**", v: { t: "swatches", list: [["#1A2A5A", "True Navy"], ["#1B2440", "Midnight Navy"]] } },
        cta("Comment your letter 👇 then find your navy free."),
      ],
    },
    {
      n: 25,
      caption: "Quick test: which colour are you drawn to wearing (not just liking)? Pick one, then swipe for what it says about your season family. 👇\n\nComment your pick. Then check properly, free, at seasoncard.app",
      tags: "#colorquiz #coloranalysis #colorseason #quiz #whatseasonami",
      slides: [
        { hook: true, title: "Pick a colour. I'll guess your season family. 🎨", v: { t: "letters", list: [["#FF8C7A", "1"], ["#9BB0C9", "2"], ["#B7410E", "3"], ["#0050B4", "4"]] } },
        { title: "Not the colour you like. The one people **compliment you in.**", v: { t: "bigtext", text: "👀", sub: "Think about the last time someone said \"that colour suits you\"." } },
        { kicker: "1 · Coral", title: "Warm and clear: you may be a **Spring.**", v: { t: "palettes", ids: ["light-spring", "true-spring", "bright-spring"] } },
        { kicker: "2 · Powder blue", title: "Cool and soft: you may be a **Summer.**", v: { t: "palettes", ids: ["light-summer", "true-summer", "soft-summer"] } },
        { kicker: "3 · Rust", title: "Warm and muted: you may be an **Autumn.**", v: { t: "palettes", ids: ["soft-autumn", "true-autumn", "deep-autumn"] } },
        { kicker: "4 · Cobalt", title: "Cool and clear: you may be a **Winter.**", v: { t: "palettes", ids: ["deep-winter", "true-winter", "bright-winter"] } },
        cta("A guess is fun. Your 4 measurements are better. Free scan →"),
      ],
    },
    {
      n: 26,
      caption: "Part 2 of guess the season from the palette. Harder this time: these are the neighbouring seasons. Score out of 4? 👇 (No peeking at slide 6.)\n\nComment your score. Free scan at seasoncard.app",
      tags: "#guesstheseason #coloranalysis #colorseason #colorpalette #quiz",
      slides: [
        { hook: true, title: "Guess the season, part 2. Harder this time. 🤔", v: { t: "bigtext", text: "?", sub: "4 palettes · answers on slide 6" } },
        { kicker: "Palette 1", title: "Guess!", v: { t: "letters", list: S["soft-summer"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Palette 2", title: "Guess!", v: { t: "letters", list: S["deep-autumn"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Palette 3", title: "Guess!", v: { t: "letters", list: S["bright-spring"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Palette 4", title: "Guess!", v: { t: "letters", list: S["true-summer"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Answers", title: "How many did you get?", v: { t: "answers", list: [[S["soft-summer"].cardSwatches, "Soft Summer"], [S["deep-autumn"].cardSwatches, "Deep Autumn"], [S["bright-spring"].cardSwatches, "Bright Spring"], [S["true-summer"].cardSwatches, "True Summer"]] } },
        cta("Now get your own 4-colour card."),
      ],
    },
    {
      n: 27,
      caption: "Open your wardrobe. Which row looks most like it? Your closet already knows things about your season. A, B, C or D? 👗👇\n\nComment your letter. Then check for real, free, at seasoncard.app",
      tags: "#closet #wardrobe #coloranalysis #colorseason #capsulewardrobe",
      slides: [
        { hook: true, title: "Your closet is trying to tell you your season. 👗", v: { t: "bigtext", text: "A B C D", sub: "Which row looks like your wardrobe?" } },
        { kicker: "A", title: "Coral, aqua, butter, camel", v: { t: "swatches", list: [["#F7917A", ""], ["#82D8C4", ""], ["#FFE38A", ""], ["#D7B98E", ""]] } },
        { kicker: "B", title: "Dusty rose, grey-blue, lavender, soft navy", v: { t: "swatches", list: [["#C4A0A0", ""], ["#9BB0C9", ""], ["#B8A1C9", ""], ["#45506A", ""]] } },
        { kicker: "C", title: "Rust, olive, mustard, brown", v: { t: "swatches", list: [["#B7410E", ""], ["#708238", ""], ["#D4A017", ""], ["#573724", ""]] } },
        { kicker: "D", title: "Black, white, emerald, true red", v: { t: "swatches", list: [["#111111", ""], ["#FAFAFA", ""], ["#009B77", ""], ["#C8102E", ""]] } },
        { kicker: "What it might mean", title: "A → Spring · B → Summer · C → Autumn · D → Winter. **But** we often buy what's trendy, not what suits us.", v: { t: "grid12" } },
        cta("Your closet is a hint. A daylight scan is a measurement. Free →"),
      ],
    },
    {
      n: 28,
      caption: "\"I can't wear orange\" is usually \"I'm wearing the wrong orange\". Peach, tangerine, rust, coral-red: one of these is yours. A, B, C or D? 🧡👇\n\nComment your letter. Free scan at seasoncard.app",
      tags: "#orange #coloranalysis #colorseason #fallcolors #styletips",
      slides: [
        { hook: true, title: "Think you can't wear orange? Try the right one. 🧡", v: { t: "letters", list: [["#FBB27F", "A"], ["#E9967A", "B"], ["#B7410E", "C"], ["#FF7A1A", "D"]] } },
        { title: "Orange is warm, but it comes **light, soft, deep or bright.** That's what changes who it suits.", v: { t: "chroma", a: "#FF7A1A", b: "#C98B6B", la: "Bright", lb: "Soft" } },
        { kicker: "A · Light Spring", title: "**Apricot and peach**", v: { t: "swatches", list: [["#FBB27F", "Apricot"], ["#FFC7AE", "Peach Blossom"]] } },
        { kicker: "B · Summers", title: "**Soft coral-pink** instead of true orange", v: { t: "swatches", list: [["#E9967A", "Soft coral"], ["#F4A29A", "Salmon pink"]] } },
        { kicker: "C · Autumns", title: "**Rust and burnt orange**", v: { t: "swatches", list: [["#B7410E", "Rust"], ["#BC581C", "Burnt Orange"]] } },
        { kicker: "D · Bright Spring", title: "**Bright, clear orange**", v: { t: "swatches", list: [["#FF7A1A", "Bright Orange"], ["#F47C20", "Tangerine"]] } },
        cta("Comment your letter 👇 then find your orange free."),
      ],
    },
    {
      n: 29,
      caption: "Mocha looks rich on some people and muddy on others ☕ It's all about which mocha. Which one is yours? A, B, C or D? 👇\n\nComment your letter." + R + "mocha brown outfit · which brown suits me",
      tags: "#mochamousse #coloranalysis #colorseason #fallfashion #seasonclub",
      slides: [
        { hook: true, title: "Mocha looks rich on some people. Muddy on others. ☕", v: { t: "letters", list: [[X("light-spring", "café au lait"), "A"], [X("soft-summer", "cocoa"), "B"], [X("soft-autumn", "milk cocoa"), "C"], [X("deep-winter", "cool espresso"), "D"]] } },
        { title: "Mocha is a **soft, medium brown.** Temperature and depth decide whether it glows or goes muddy.", v: { t: "gradient", pos: 55, lo: "Rosy cocoa", hi: "Golden mocha" } },
        { kicker: "A · Springs", title: "Light, **milky and golden**: café au lait", v: { t: "swatches", list: [[X("light-spring", "café au lait"), "Café au Lait"], [X("light-spring", "light camel"), "Light Camel"]] } },
        { kicker: "B · Summers", title: "**Rosy and greyed**: cocoa, rose taupe", v: { t: "swatches", list: [[X("soft-summer", "cocoa"), "Cocoa"], [X("soft-summer", "rose taupe"), "Rose Taupe"]] } },
        { kicker: "C · Autumns", title: "**Warm and soft**: milk cocoa, toffee", v: { t: "swatches", list: [[X("soft-autumn", "milk cocoa"), "Milk Cocoa"], [X("true-autumn", "toffee"), "Toffee"]] } },
        { kicker: "D · Winters", title: "Skip mid-mocha. Go **deep and cool**: cool espresso", v: { t: "swatches", list: [[X("deep-winter", "cool espresso"), "Cool Espresso"], [X("deep-winter", "charcoal"), "Charcoal"]] } },
        cta("Season Club: comment your letter 👇 then find your exact brown free."),
      ],
    },
    {
      n: 30,
      caption: "Olive green is everywhere this autumn, but olive isn't one colour 🫒 Which olive is yours? A, B, C or D? 👇\n\nComment your letter." + R + "olive green outfit · who can wear olive green",
      tags: "#olivegreen #coloranalysis #colorseason #autumnpalette #seasonclub",
      slides: [
        { hook: true, title: "Olive green: 4 versions, only one is yours. 🫒", v: { t: "letters", list: [[X("light-spring", "pistachio"), "A"], [X("soft-summer", "sage"), "B"], [X("true-autumn", "olive"), "C"], [X("deep-winter", "pine"), "D"]] } },
        { title: "Olive is **warm and muted.** Autumns own it. Everyone else needs a twist.", v: { t: "chroma", a: X("true-autumn", "olive"), b: X("soft-autumn", "warm sage"), la: "Olive (rich)", lb: "Warm sage (soft)" } },
        { kicker: "A · Springs", title: "Go **lighter and clearer**: pistachio, fresh apple", v: { t: "swatches", list: [[X("light-spring", "pistachio"), "Pistachio"], [X("light-spring", "fresh apple"), "Fresh Apple"]] } },
        { kicker: "B · Summers", title: "Go **grey-green**: sage, eucalyptus", v: { t: "swatches", list: [[X("soft-summer", "sage"), "Sage"], [X("soft-summer", "eucalyptus"), "Eucalyptus"]] } },
        { kicker: "C · Autumns", title: "**True olive** is yours: olive, moss, golden olive", v: { t: "swatches", list: [[X("true-autumn", "olive"), "Olive"], [X("true-autumn", "moss"), "Moss"], [X("soft-autumn", "golden olive"), "Golden Olive"]] } },
        { kicker: "D · Winters", title: "Swap olive for **cool pine and emerald**", v: { t: "swatches", list: [[X("deep-winter", "pine"), "Pine"], [X("deep-winter", "emerald"), "Emerald"]] } },
        cta("Season Club: comment your letter 👇 then find your green free."),
      ],
    },
    {
      n: 31,
      caption: "Cobalt blue makes some people glow and swallows others 💙 It's a clear, cool, high-energy colour. Did cobalt ever get you compliments? Yes or no? 👇\n\nComment yes or no." + R + "cobalt blue outfit · who can wear cobalt blue",
      tags: "#cobaltblue #coloranalysis #colorseason #wintercolors #seasonclub",
      slides: [
        { hook: true, title: "Cobalt blue makes some people glow. Others it swallows.", v: { t: "single", c: X("bright-winter", "cobalt") } },
        { title: "Cobalt is **cool, clear and saturated.** It needs colouring with some contrast and clarity.", v: { t: "chroma", a: X("bright-winter", "cobalt"), b: X("soft-summer", "storm blue"), la: "Cobalt (clear)", lb: "Storm blue (soft)" } },
        { kicker: "Made for", title: "Bright Winter, True Winter and Bright Spring", v: { t: "palettes", ids: ["bright-winter", "true-winter", "bright-spring"] } },
        { kicker: "Soft or light colouring?", title: "Summers: try **cornflower or denim** instead.", v: { t: "pair", a: [X("true-summer", "cornflower"), "Cornflower"], b: [X("true-summer", "denim blue"), "Denim Blue"] } },
        { kicker: "Autumns?", title: "Cobalt can look harsh. Try **teal or petrol**.", v: { t: "pair", a: [X("true-autumn", "teal"), "Teal"], b: [X("deep-autumn", "petrol"), "Petrol"] } },
        { kicker: "Quick check", title: "If cobalt makes your **eyes pop**, it's yours. If you see the blue before your face, it's too much.", v: { t: "pair", a: [X("bright-winter", "cobalt"), "Eyes pop → yours"], b: [X("light-summer", "chambray"), "Too much → go softer"] } },
        cta("Your 36-colour palette shows your exact blue. Free scan first →"),
      ],
    },
    {
      n: 32,
      caption: "Plum is the autumn colour almost nobody talks about 🍇 and there's a plum for most seasons. Which one is yours? A, B, C or D? 👇\n\nComment your letter." + R + "plum color outfit · which purple suits me",
      tags: "#plum #coloranalysis #colorseason #fallfashion #seasonclub",
      slides: [
        { hook: true, title: "Plum is the fall colour nobody talks about. 🍇", v: { t: "letters", list: [[X("true-spring", "warm violet"), "A"], [X("true-summer", "soft plum"), "B"], [X("deep-autumn", "plum"), "C"], [X("true-winter", "plum"), "D"]] } },
        { title: "Purple goes **warm (red-plum)** or **cool (blue-plum).** Depth decides how dark.", v: { t: "gradient", pos: 50, lo: "Blue-plum", hi: "Red-plum" } },
        { kicker: "A · Springs", title: "Clear, **warm violet**", v: { t: "swatches", list: [[X("true-spring", "warm violet"), "Warm Violet"], [X("true-spring", "orchid"), "Orchid"]] } },
        { kicker: "B · Summers", title: "Soft, **dusty plum**", v: { t: "swatches", list: [[X("true-summer", "soft plum"), "Soft Plum"], [X("true-summer", "soft grape"), "Soft Grape"]] } },
        { kicker: "C · Autumns", title: "Warm, **brown-plum and mulberry**", v: { t: "swatches", list: [[X("deep-autumn", "plum"), "Plum"], [X("deep-autumn", "mulberry"), "Mulberry"], [X("deep-autumn", "aubergine"), "Aubergine"]] } },
        { kicker: "D · Winters", title: "Deep, **cool blackberry plum**", v: { t: "swatches", list: [[X("true-winter", "plum"), "Plum"], [X("true-winter", "blackberry"), "Blackberry"]] } },
        cta("Season Club: comment your letter 👇 then find your plum free."),
      ],
    },
    {
      n: 33,
      caption: "Pistachio is the softest 'it' green, and it's not for everyone 🌱 It's made for warm, light colouring. Pistachio or mint: which do you reach for? 👇\n\nComment pistachio or mint." + R + "pistachio green outfit · who can wear pistachio",
      tags: "#pistachiogreen #coloranalysis #colorseason #springcolors #seasonclub",
      slides: [
        { hook: true, title: "Pistachio green: who it's actually for. 🌱", v: { t: "single", c: X("light-spring", "pistachio") } },
        { title: "Pistachio is **light, warm and slightly yellow.** It loves golden, light colouring.", v: { t: "chroma", a: X("light-spring", "pistachio"), b: X("light-summer", "mint"), la: "Pistachio (warm)", lb: "Mint (cool)" } },
        { kicker: "Made for", title: "Light Spring and True Spring", v: { t: "palettes", ids: ["light-spring", "true-spring"] } },
        { kicker: "Cool and light?", title: "Summers: **mint or celadon** instead.", v: { t: "pair", a: [X("light-summer", "mint"), "Mint"], b: [X("light-summer", "celadon"), "Celadon"] } },
        { kicker: "Warm but soft?", title: "Soft Autumn: **lichen or warm sage.**", v: { t: "pair", a: [X("soft-autumn", "lichen"), "Lichen"], b: [X("soft-autumn", "warm sage"), "Warm Sage"] } },
        { kicker: "Winters", title: "Skip pistachio. **Icy mint** or **emerald** works better.", v: { t: "pair", a: [X("true-winter", "icy mint"), "Icy Mint"], b: [X("true-winter", "emerald"), "Emerald"] } },
        cta("Your 36-colour palette shows your exact green. Free scan first →"),
      ],
    },
    {
      n: 34,
      caption: "Bright Spring and Bright Winter both wear clear, vivid colour. The split is warm vs cool. Coral or fuchsia: which one lights you up? 🌺💎\n\nComment coral or fuchsia." + R + "bright spring vs bright winter · am I a bright spring",
      tags: "#brightspring #brightwinter #coloranalysis #colorseason #seasonclub",
      slides: [
        { hook: true, title: "Bright Spring or Bright Winter? The coral test.", v: { t: "fans", a: "bright-spring", b: "bright-winter" } },
        { title: "Both are **clear, saturated, high-energy.** The split is **warm vs cool.**", v: { t: "palettes", ids: ["bright-spring", "bright-winter"] } },
        { kicker: "Bright Spring", title: "**Warm and clear.** Hot coral, sunshine yellow, turquoise", v: { t: "swatches", list: N("bright-spring") } },
        { kicker: "Bright Winter", title: "**Cool and clear.** Hot pink, cobalt, emerald, lemon", v: { t: "swatches", list: N("bright-winter") } },
        { kicker: "Coral test", title: "Hot coral vs hot pink under your chin, by a window. Which makes your skin look **more even?**", v: { t: "pair", a: [X("bright-spring", "hot coral"), "Hot coral → Bright Spring"], b: [X("bright-winter", "hot pink"), "Hot pink → Bright Winter"] } },
        { kicker: "Whites", title: "Clear ivory or optic white? Your white is another clue.", v: { t: "pair", a: [X("bright-spring", "clear ivory"), "Clear Ivory → Spring"], b: [X("bright-winter", "optic white"), "Optic White → Winter"] } },
        cta("See your season **and your runner-up**, free."),
      ],
    },
    {
      n: 35,
      caption: "Soft Summer is the season of dusty, misty colours that most people call 'boring', until they see them on the right face. If 4 of these 5 are you, you might be one. How many did you tick? 🌫️👇\n\nComment your number." + R + "soft summer color palette · am I a soft summer",
      tags: "#softsummer #coloranalysis #colorseason #summercolors #seasonclub",
      slides: [
        { hook: true, title: "5 signs you're a Soft Summer 🌫️", v: { t: "swatches", list: S["soft-summer"].cardSwatches.map((c) => [c, ""]) } },
        { kicker: "Sign 1 · Skin", title: "Cool-neutral skin that looks **calm, not golden or rosy-bright.**", v: { t: "gradient", pos: 40, lo: "Cool", hi: "Warm" } },
        { kicker: "Sign 2 · Hair", title: "Hair is **ash, mousy or soft brown**, rarely very dark or very golden.", v: { t: "swatches", list: S["soft-summer"].hair.map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 3 · Eyes", title: "Eyes are **soft and blended**: grey-blue, grey-green, soft hazel.", v: { t: "swatches", list: [["#7D8FA3", "Grey-blue"], ["#8A9A8B", "Grey-green"], ["#8B7A55", "Soft hazel"]] } },
        { kicker: "Sign 4 · What looks wrong", title: "**Bright white, black and bright orange** look loud on you.", v: { t: "swatches", list: S["soft-summer"].avoid.slice(0, 3).map((c) => [c.hex, c.name]) } },
        { kicker: "Sign 5 · What looks right", title: "Misty colours like **dusty rose, sage and blue grey** make you look polished.", v: { t: "palettes", ids: ["soft-summer"] } },
        cta("Ticked 4 or 5? Season Club: comment your season. Check it free →"),
      ],
    },
    {
      n: 36,
      caption: "Grey is the 'safe' neutral that isn't safe for everyone 🩶 Warm grey, blue grey, stone or charcoal? Which one is yours? A, B, C or D? 👇\n\nComment your letter." + R + "which grey suits me · grey outfit color analysis",
      tags: "#greyoutfit #coloranalysis #colorseason #capsulewardrobe #seasonclub",
      slides: [
        { hook: true, title: "Grey isn't neutral on everyone. Which grey is yours? 🩶", v: { t: "letters", list: [[X("true-spring", "warm grey"), "A"], [X("true-summer", "blue-grey"), "B"], [X("soft-autumn", "stone"), "C"], [X("true-winter", "charcoal"), "D"]] } },
        { title: "Greys lean **warm (beige)** or **cool (blue)**, and come **light or deep.**", v: { t: "gradient", pos: 50, lo: "Blue grey", hi: "Warm grey" } },
        { kicker: "A · Springs", title: "**Warm, light greys**: warm grey, warm pebble", v: { t: "swatches", list: [[X("true-spring", "warm grey"), "Warm Grey"], [X("light-spring", "warm pebble"), "Warm Pebble"]] } },
        { kicker: "B · Summers", title: "**Cool, soft greys**: blue grey, dove, pewter", v: { t: "swatches", list: [[X("true-summer", "blue-grey"), "Blue-Grey"], [X("light-summer", "dove grey"), "Dove Grey"], [X("light-summer", "pewter"), "Pewter"]] } },
        { kicker: "C · Autumns", title: "Barely grey: **stone and warm taupe**", v: { t: "swatches", list: [[X("soft-autumn", "stone"), "Stone"], [X("soft-autumn", "warm taupe"), "Warm Taupe"]] } },
        { kicker: "D · Winters", title: "**Crisp, cool greys**: charcoal, icy grey", v: { t: "swatches", list: [[X("true-winter", "charcoal"), "Charcoal"], [X("true-winter", "icy grey"), "Icy Grey"]] } },
        cta("Season Club: comment your letter 👇 then find your neutrals free."),
      ],
    },
    {
      n: 37,
      caption: "Coat season 🧥 Camel is the classic, but a camel that's wrong for you sits right next to your face all winter. Which camel is yours? A, B, C or D? 👇\n\nComment your letter." + R + "camel coat color analysis · which camel suits me",
      tags: "#camelcoat #coloranalysis #colorseason #fallfashion #seasonclub",
      slides: [
        { hook: true, title: "Buying a camel coat? Pick the right camel first. 🧥", v: { t: "letters", list: [[X("light-spring", "light camel"), "A"], [X("light-summer", "rose beige"), "B"], [X("true-autumn", "camel"), "C"], [X("true-winter", "charcoal"), "D"]] } },
        { title: "A coat sits **right under your face.** It's the biggest colour you'll wear all winter.", v: { t: "bigtext", text: "🧥", sub: "Same coat, every day, for months." } },
        { kicker: "A · Springs", title: "**Light, golden camel**", v: { t: "swatches", list: [[X("light-spring", "light camel"), "Light Camel"], [X("true-spring", "camel"), "Camel"]] } },
        { kicker: "B · Summers", title: "Camel can look sallow. Try **rose beige or soft grey.**", v: { t: "swatches", list: [[X("light-summer", "rose beige"), "Rose Beige"], [X("true-summer", "light grey"), "Light Grey"]] } },
        { kicker: "C · Autumns", title: "Classic **camel and deep camel** are yours.", v: { t: "swatches", list: [[X("true-autumn", "camel"), "Camel"], [X("deep-autumn", "deep camel"), "Deep Camel"], [X("soft-autumn", "soft camel"), "Soft Camel"]] } },
        { kicker: "D · Winters", title: "Skip camel. **Charcoal, navy or black** coats win.", v: { t: "swatches", list: [[X("true-winter", "charcoal"), "Charcoal"], [X("true-winter", "true navy"), "True Navy"], [X("true-winter", "black"), "Black"]] } },
        cta("Season Club: comment your letter 👇 then check your season free."),
      ],
    },
    {
      n: 38,
      caption: "Deep Autumn and Deep Winter both look amazing in dark, rich colour. The split is warm vs cool. Chili red or true red: which one is you? 🍂❄️\n\nComment chili or true red." + R + "deep autumn vs deep winter · am I a deep autumn",
      tags: "#deepautumn #deepwinter #coloranalysis #colorseason #seasonclub",
      slides: [
        { hook: true, title: "Deep Autumn or Deep Winter? It's one question.", v: { t: "fans", a: "deep-autumn", b: "deep-winter" } },
        { title: "Both are **deep and rich.** The split is **warm (golden) vs cool (blue).**", v: { t: "palettes", ids: ["deep-autumn", "deep-winter"] } },
        { kicker: "Deep Autumn", title: "**Warm and earthy.** Oxblood, burnt orange, forest, deep teal", v: { t: "swatches", list: N("deep-autumn") } },
        { kicker: "Deep Winter", title: "**Cool and jewel-toned.** Emerald, sapphire, true red", v: { t: "swatches", list: N("deep-winter") } },
        { kicker: "Red test", title: "Chili vs true red under your chin. Which makes your skin look **more even?**", v: { t: "pair", a: [X("deep-autumn", "chili"), "Chili → Deep Autumn"], b: [X("deep-winter", "true red"), "True red → Deep Winter"] } },
        { kicker: "Metal test", title: "Antique gold or polished silver?", v: { t: "pair", a: ["linear-gradient(135deg,#8C6A1E,#E9C766 45%,#B8902C 60%,#F3DC8A)", "Gold → Deep Autumn"], b: ["linear-gradient(135deg,#7D8086,#E6E8EB 45%,#A3A7AD 60%,#F2F3F5)", "Silver → Deep Winter"] } },
        cta("See your season **and your runner-up**, free."),
      ],
    },
  ];
};
